spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    jpa:
      database: POSTGRESQL
      show-sql: true
      hibernate:
        ddl-auto: update

server:
  port: 8080